# TwinTube — start full local dev stack (Windows)
# Serves ./static live via native Go; Postgres optional in Docker.
param(
    [switch]$Postgres,
    [switch]$DockerApp,
    [int]$Port = 8080
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$StateDir = Join-Path $Root ".local"
$StateFile = Join-Path $StateDir "dev-state.json"

Set-Location $Root

function Write-Info($msg) { Write-Host "[TwinTube] $msg" -ForegroundColor Cyan }
function Write-Ok($msg) { Write-Host "[TwinTube] $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[TwinTube] $msg" -ForegroundColor Yellow }

if (-not (Test-Path $StateDir)) {
    New-Item -ItemType Directory -Path $StateDir | Out-Null
}

if (Test-Path $StateFile) {
    try {
        $existing = Get-Content $StateFile -Raw | ConvertFrom-Json
        if ($existing.appPid) {
            $proc = Get-Process -Id $existing.appPid -ErrorAction SilentlyContinue
            if ($proc) {
                Write-Warn "TwinTube already running (PID $($existing.appPid)) on http://localhost:$($existing.port)"
                Start-Process "http://localhost:$($existing.port)/"
                exit 0
            }
        }
    } catch {
        Remove-Item $StateFile -Force -ErrorAction SilentlyContinue
    }
}

if (-not (Get-Command go -ErrorAction SilentlyContinue)) {
    throw "Go is not installed or not on PATH. Install Go 1.21+ from https://go.dev/dl/"
}

if (-not (Test-Path (Join-Path $Root ".env"))) {
    Write-Info "Creating .env from .env.example ..."
    Copy-Item (Join-Path $Root ".env.example") (Join-Path $Root ".env")
}

$env:PORT = "$Port"
$mode = "native-sqlite"
$postgresStarted = $false

if ($DockerApp) {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        throw "Docker is required for -DockerApp but was not found."
    }
    Write-Info "Building and starting Docker Compose stack ..."
    docker compose up -d --build
    if ($LASTEXITCODE -ne 0) { throw "docker compose up failed." }

    $deadline = (Get-Date).AddMinutes(3)
    do {
        Start-Sleep -Seconds 2
        try {
            $resp = Invoke-WebRequest -Uri "http://localhost:$Port/" -UseBasicParsing -TimeoutSec 3
            if ($resp.StatusCode -eq 200) { break }
        } catch { }
    } while ((Get-Date) -lt $deadline)

    @{
        mode = "docker-compose"
        port = $Port
        startedAt = (Get-Date).ToString("o")
    } | ConvertTo-Json | Set-Content $StateFile -Encoding UTF8

    Write-Ok "TwinTube is running at http://localhost:$Port/ (Docker)"
    Start-Process "http://localhost:$Port/"
    exit 0
}

if ($Postgres) {
    if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
        Write-Warn "Docker not found; falling back to SQLite."
    } else {
        Write-Info "Starting PostgreSQL container ..."
        docker compose up -d postgres
        if ($LASTEXITCODE -ne 0) { throw "Failed to start postgres container." }

        $deadline = (Get-Date).AddMinutes(2)
        do {
            Start-Sleep -Seconds 2
            $health = docker inspect --format='{{.State.Health.Status}}' twintube_postgres 2>$null
            if ($health -eq "healthy") { break }
        } while ((Get-Date) -lt $deadline)

        $env:DB_TYPE = "postgres"
        $env:DATABASE_URL = "postgres://twintube_user:twintube_secure_password@localhost:5432/twintube_db?sslmode=disable"
        $mode = "native-postgres"
        $postgresStarted = $true
        Write-Ok "PostgreSQL ready on localhost:5432"
    }
}

if ($mode -eq "native-sqlite") {
    @(
        "# Auto-generated by scripts/start-local.ps1",
        "DB_TYPE=sqlite",
        "DATABASE_URL=",
        "POSTGRES_HOST=",
        "POSTGRES_PORT=",
        "POSTGRES_USER=",
        "POSTGRES_PASSWORD=",
        "POSTGRES_DB=",
        "POSTGRES_SSLMODE="
    ) | Set-Content (Join-Path $Root ".env.local") -Encoding UTF8
    Write-Info "Using local SQLite (twintube.db) - .env.local overrides production .env"
}

if ($mode -eq "native-postgres") {
    @(
        "# Auto-generated by scripts/start-local.ps1",
        "DB_TYPE=postgres",
        "DATABASE_URL=postgres://twintube_user:twintube_secure_password@localhost:5432/twintube_db?sslmode=disable",
        "POSTGRES_HOST=localhost",
        "POSTGRES_PORT=5432",
        "POSTGRES_USER=twintube_user",
        "POSTGRES_PASSWORD=twintube_secure_password",
        "POSTGRES_DB=twintube_db",
        "POSTGRES_SSLMODE=disable"
    ) | Set-Content (Join-Path $Root ".env.local") -Encoding UTF8
}

if (-not $env:JWT_SECRET) {
    $env:JWT_SECRET = "local_dev_jwt_secret_change_me_12345"
}

$logFile = Join-Path $StateDir "twintube.log"
$errFile = Join-Path $StateDir "twintube.err.log"
Write-Info "Starting Go server on port $Port ($mode) ..."
Write-Info "Logs: $logFile"

$proc = Start-Process -FilePath "go" -ArgumentList "run", "." -WorkingDirectory $Root `
    -RedirectStandardOutput $logFile -RedirectStandardError $errFile -PassThru -WindowStyle Hidden

$deadline = (Get-Date).AddMinutes(2)
$ready = $false
do {
    Start-Sleep -Seconds 1
    if ($proc.HasExited) {
        Get-Content $logFile -Tail 40 -ErrorAction SilentlyContinue
        Get-Content $errFile -Tail 40 -ErrorAction SilentlyContinue
        throw "Server exited early (see logs in .local/)."
    }
    try {
        $resp = Invoke-WebRequest -Uri "http://localhost:$Port/" -UseBasicParsing -TimeoutSec 2
        if ($resp.StatusCode -eq 200) { $ready = $true; break }
    } catch { }
} while ((Get-Date) -lt $deadline)

if (-not $ready) {
    Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
    Get-Content $logFile -Tail 40 -ErrorAction SilentlyContinue
    Get-Content $errFile -Tail 40 -ErrorAction SilentlyContinue
    throw "Server did not become ready on http://localhost:$Port/"
}

@{
    mode = $mode
    appPid = $proc.Id
    port = $Port
    postgresStarted = $postgresStarted
    logFile = $logFile
    startedAt = (Get-Date).ToString("o")
} | ConvertTo-Json | Set-Content $StateFile -Encoding UTF8

Write-Ok "TwinTube is running at http://localhost:$Port/"
Write-Info "Database: $mode (local twintube.db for SQLite - separate from production VPS)"
Write-Info "Stop with: scripts\stop-local.ps1"
Start-Process "http://localhost:$Port/"
